Learnt phrase
onja-org/malagasy-rn-Bismuth pull request #4
Opened 2021-05-21 11:30 UTC by ravinalamada

Hello team,

This is a component that displays the phrases that a user has learned and stored that data locally by using thunk. Can you review it  at any time you have a chance for it please?

Thanks in advanced,

2021-05-24 08:53 UTC, andrzej-onja commented on src/screens/Learning.js
> +// import AsyncStorage from '@react-native-async-storage/async-storage';
remove unused code

2021-05-24 08:53 UTC, andrzej-onja commented on src/screens/Home.js
> +                id: 2,
instead of 2 as Id use something like ###learnt-phrases###

2021-05-24 08:53 UTC, andrzej-onja commented on src/screens/Learning.js
> +              learntPhrasesCat
as discussed we dont need 'learntPhrasesCat' in redux state try to set current category when clicking on the main screen. Set it to id ###learnt-phrases###
Then pass the existing prop current cat id from state here and do the condition logic based on that.

2021-05-25 06:55 UTC, lightme-fan requested changes
When you display the lerntCatName, use the LANGUAGE_NAMES.EN].

2021-05-25 06:55 UTC, lightme-fan commented on src/screens/Learning.js
> +  const learntCatName = learntCategory?.name.en;
This is always going to stay in English. Perhaps, you use .[LANGUAGE_NAMES.EN].

2021-05-25 08:03 UTC, Tiaraha-funny approved these changes

2021-05-25 08:08 UTC, lightme-fan approved these changes

2021-05-25 08:44 UTC, andrzej-onja approved these changes

2021-05-25 08:45 UTC, merged