Async interface refactor
onja-org/malagasy-rn-Bismuth pull request #8
Opened 2021-06-03 06:26 UTC by ravinalamada

Hi everyone,

This is the refactor the we have done for the fetch function. we changed it from synchronous function to asynchronous function. Can you look at it please? we would be glad to get any feedback from you if there is something that is needed to change.

Thanks in advanced,

2021-06-03 07:03 UTC, constantingoeldel requested changes
Just naming considerations, what do you think?

2021-06-03 07:03 UTC, constantingoeldel commented on src/containers/HomeScreenContainer.js
> +  getAllCategoriesAction,
Having action in the name is not necessary, instead just name it getAllCategories

2021-06-03 07:03 UTC, constantingoeldel commented on src/redux/actions/index.js
> +import {getAllCategories} from '../../data/dataUtils';
To prevent a name conflict here, consider importing it as something else. How about this?
```suggestion
import {getAllCategories as getAllLocalCategories} from '../../data/dataUtils';
```

2021-06-03 08:14 UTC, andrzej-onja approved these changes
looks ok please address @constantingoeldel comments

2021-06-03 11:43 UTC, lightme-fan approved these changes

2021-06-03 11:45 UTC, Tiaraha-funny approved these changes

2021-06-03 12:00 UTC, Betsimisaraka approved these changes

2021-06-04 04:57 UTC, constantingoeldel approved these changes

2021-06-04 05:02 UTC, merged